---
  plugin: amazon.aws.aws_ec2
  aws_access_key: "{{ awsaccesskey }}"
  aws_secret_key: "{{ awssecretkey }}"
  region: 
  - ap-south-1 
  keyed_groups:
    - key: tags.Env
      prefix: tag_Env