---
# task to deploy ec2 instances fork8s cluster on AWS

  # create k8s master instance
  - name: 'Create K8s master'
    amazon.aws.ec2_instance:
      name: k8s-master
      vpc_subnet_id: "{{ subnetid }}"
      instance_type: "{{ master_instance_type }}"
      key_name: "{{ key_name }}"
      security_group: "{{ securitygroupid }}"
      count: "{{ master_count }}"
      region: "{{ region}}"
      tags:
        Env: development  
        Role: master   
      network:
        assign_public_ip: true
      volumes:
        - device_name: "{{ volumelabel }}"
          ebs:
            volume_size: 20
            delete_on_termination: true
      image_id: "{{ ami }}"            
      state: present

  # create k8s client instances
  - name: 'Create K8s client'
    amazon.aws.ec2_instance:
      name: k8s-worker
      vpc_subnet_id: "{{ subnetid }}"
      instance_type: "{{ slave_instance_type }}"
      key_name: "{{ key_name }}"
      security_group: "{{ securitygroupid }}"
      count: "{{ worker_count }}"
      region: "{{ region}}"
      tags:
        Env: development  
        Role: worker 
      network:
        assign_public_ip: true
      volumes:
        - device_name: "{{ volumelabel }}"
          ebs:
            volume_size: 20
            delete_on_termination: true
      image_id: "{{ ami }}"            
      state: present

  - name: Waiting for the instances to launch
    pause:
      minutes: 1

  - name: Refresh inventory to ensure new instances exist in inventory
    meta: Refresh_inventory