---
# common steps
    # install common packages
  - name: 'Installcommon packages'
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items: "{{ common_dependencies }}"
    when: ansible_distribution == 'Ubuntu'

  - name: 'Disabling swap'
    command: swapoff -a

  - name: 'set hostname on master'
    ansible.builtin.hostname:
      name: master
      use: systemd
    when: ansible_host == tag_Role_master
