---
# tasks file for ec2key
  - name: 'Create new EC2 key'
    amazon.aws.ec2_key:
      name: "{{ key_name }}"
      region: "{{ region }}"
    register: ec2_key
  - name: 'Save ec2 key'
    copy: content="{{ ec2_key.key.private_key }}" dest="./keys/{{ key_name }}.pem" mode=0600
    when: ec2_key.changed